SELECT * FROM ORGANIZATION O
INNER JOIN MODEL M        ON M.ORGANIZATION_ID = O.ID
INNER JOIN MODEL_ITEMS MI ON MI.MODEL_ID       = M.ID

/

SELECT * FROM MODEL M
WHERE CREATED_AT < (SYSDATE - 120)

/

SELECT * FROM MODEL_ITEMS MI
WHERE PART_NUMBER LIKE '%EAX'

/

SELECT * FROM ORGANIZATION O
WHERE ORG_CODE IN ('NW1','NW9')

/

SELECT MODEL_SUFFIX, COUNT(MODEL_SUFFIX) FROM MODEL M

/

SELECT MODEL_SUFFIX, COUNT(MODEL_SUFFIX) AS 'ITEM_COUNT' FROM MODEL M

/

SELECT MODEL_SUFFIX, COUNT(MODEL_SUFFIX) AS 'ITEM_COUNT' FROM MODEL M
GROUP BY MODEL_SUFFIX
HAVING COUNT (MODEL_SUFFIX)>1
ORDER BY COUNT(MODEL_SUFFIX) DESC

